# Default detekt configuration:
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

build:
  maxIssues: 200
  excludeCorrectable: false
  weights:
    complexity: 20
    LongParameterList: 10
    style: 10
    comments: 10
    LongMethod: 10

complexity:
  TooManyFunctions:
    active: false

exceptions:
  TooGenericExceptionCaught:
    active: false

formatting:
  ParameterListWrapping:
    active: false
  ChainWrapping:
    active: false

style:
  ReturnCount:
    active: false
